version: "3.9"

services:
  web:
    build: .
    env_file: .env
    volumes:
      - ./wp-content/themes/mytheme:/var/www/html/wp-content/themes/mytheme
      - wordpress:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: